name: Create a new version of extension

on:
  release:
    types: [created]

jobs:
  build:
    name: Build and upload the extension archive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Build extension
        run: |
          npm ci
          npm run build
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Create zip with the new version of extension
        run: |
          sed -i "s/0.0.1/$RELEASE_VERSION/" dist/manifest.json
          zip -r -j labelsync-$RELEASE_VERSION.zip dist/*
          node build/add_firefox_details.js
          zip -r -j labelsync-firefox-$RELEASE_VERSION.zip dist/*
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: labelsync-*.zip
          file_glob: true
          tag: ${{ github.ref }}
